//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoClubEntities : DbContext
    {
        public VideoClubEntities()
            : base("name=VideoClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alquileres> Alquileres { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Tarifas> Tarifas { get; set; }
    }
}
